name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST_PORT }}
          source: "."
          target: "/home/${{ secrets.HOST_USER_NAME }}/final-project"

      - name: Execute docker compose up on server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd /home/${{ secrets.HOST_USER_NAME }}/final-project
            docker compose down
            docker compose up --build -d
            docker system prune -f
